### ISSUE TITLE
Eliminate icons showing full size before CSS loads

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-icons#3]
may be pass a hard coded parameter, or loading icons CSS as critical...

**Comment by regisphilibert** [comment]
So we can easily manipulate the content of the svg file before using. So adding a style attribute on a class attribute to the svg is doable. 

Now what's left for us is a decision. Adding an inline style attribute is rather brutal as this will overwrite any css added on the icons.

We can add a `css` class though `<svg class="tnd-icon tnd-icon--{icon-name}" ` but this would let the project deal with the issue by adding an `style` tag before the script is loaded:
```
<style>
.tnd-icon{max-width:100%}
<style>
```

I think giving the responsibility to the project is good as not every project will want to the same default rule. We can document the process in the read-me.

**Comment by regisphilibert** [comment]
Ok so the problem with anything passed inline is that we then need to overwrite it with css.
With a declared `width` attribute, we can only add `{width: auto}

So with `<style width=1em ` which usually make sense if you use font-size to adapt your icons, if you need to overwrite it, you cannot expect the default contextual width to cascade from any parent or else by using `width: auto` in your css as this will fallback on the width attribute value.

You could still overwrite this with:
```
.tnd-icon[width]{
  width: auto !important
}
```

But for some reason the above is not printed on my css file 🤷‍♂️., just like your `[x-cloak]` target rule is not either... I'm not sure what's going on but it's preventing me from testing this. We're not running PostCSS on the server so that can't be it...
